### ISSUE TITLE
Could we rebase this module on top of neo ?

### ISSUE THREAD

**Issue by samuelgarcia** [CINPLA/pyopenephys#17]
This would centralize bug tracking at one place only.

**Comment by alejoe91** [comment]
Yes, maybe neo.rawio. But I don't have time to do in before February...Can we do it then?

**Comment by samuelgarcia** [comment]
:)
Of course not, I don't have time.
Just to stress you on this front.
I propose a hackaton in Lyon to rebase evrrything on neo.rawio
:)
