### ISSUE TITLE
Dose this library drow LFP ?

### ISSUE THREAD

**Issue by ttglia** [CINPLA/pyopenephys#18]
I use .continuous file and want to draw each channel LFP .

Please , if possible , I want to see a sample dataplot.

**Comment by alejoe91** [comment]
HI! Yes it is possible (but I highly recommend using the binary format in the open ephys gui).

You can load the analog signals as:

```
import pyopenephys

file = pyopenephys.File('path-to-oe-folder')
experiment = file.experiments[0]
recording = experiment.recordings[0]
signals = recording.analog_signals[0]
```

You can then filter the signals using a bandpass filter (e.g. using `scipy` [filters](https://docs.scipy.org/doc/scipy/reference/signal.html)) and plot the data using `matplotlib`. These packages have several examples on how to use them.

Alternatively, you can do the same thing using the `SpikeInterface` package, which supports Open Ephys recordings. See documentation here (https://spikeinterface.readthedocs.io/en/latest/).
