### ISSUE TITLE
Read from other streams of data

### ISSUE THREAD

**Issue by luiztauffer** [CINPLA/pyopenephys#21]
From this piece of code, I’m guessing we are only able to read data files that contain `Source` type of data, that means raw data, is that correct?

https://github.com/CINPLA/pyopenephys/blob/d223868b56a41cebc5e3d9ecbe67053ae36e2166/pyopenephys/core.py#L264-L296

I assume OpenEphys system are capable of saving files from other “processors” as well, for example, I have an examples `settings.xml` containing several processors in the signalchain:

![image](https://user-images.githubusercontent.com/24541631/107532908-a91adb80-6bbe-11eb-8167-4bbe555b6a3a.png)

Unfortunately I don’t have files with data from these other processors yet, but once I get, there are two things I would like to do:

1. be able to choose which stream of data to read (either raw or filtered). This could in principle be done by selecting the processor by name. 

2. If is a filter stream, be able to save the low and high cut frequencies, which can be read from the settings.xml for each channel. This would be useful information for LFP container of the NWB files

@alejoe91 what's your opinion on this?

**Comment by samuelgarcia** [comment]
Hi Luiz.
We will start very very soon openephys reader in neo see this https://github.com/NeuralEnsemble/python-neo/pull/945.

neo is multi stream by nature, if you have some multi stream datasets we could directly test the new code with this.
And also put it in gin platform.

**Comment by luiztauffer** [comment]
@samuelgarcia thanks for letting me know, that can be quite useful!
NEO does not use Pyopenephys?

**Comment by samuelgarcia** [comment]
no.
neo have its own implementation.
This avoid a dep.

(And pyopenephys did a copy/paste from neo some time ago for the old oe format)

**Comment by alejoe91** [comment]
Not for the new one ;)

**Comment by samuelgarcia** [comment]
Yes, we are good friend now.
