### ISSUE TITLE
returning gains for all channels, not only analog_signals

### ISSUE THREAD

**Issue by luiztauffer** [CINPLA/pyopenephys#23]
If this package only reads 'CH' channels (from old openephys format), it should also just return the gains for these channels

```
gains = list(f.experiments[0].recordings[0].analog_signals[0].gains)
signals = f.experiments[0].recordings[0].analog_signals[0].signal

print(len(gains))
print(signals.shape)
```
```
43
(32, 5688320)
```

**Comment by alejoe91** [comment]
Thanks for spotting this. Will push a fix soon

**Comment by alejoe91** [comment]
@luiztauffer it actually does look for the channels which have `@record == 1` in the settings. https://github.com/CINPLA/pyopenephys/blob/master/pyopenephys/core.py#L274-L300

**Comment by luiztauffer** [comment]
@alejoe91 yes, but that fixes only the processor (the stream), not the channels within it. The other channels, `AUX` and `ADC` are also present in the processor with @record==1
I believe the problem is happening here:
https://github.com/CINPLA/pyopenephys/blob/05bb10e5f7d146cc27615ac3d9b81d1e6052c30a/pyopenephys/core.py#L867-L873

a little above that, the script is picking only files with `CH`
