### ISSUE TITLE
How to solve this "ValueError: Unable to convert between units of "s/Hz" and "1/Hz" when run code "spiketrains = recording.spiketrains"?

### ISSUE THREAD

**Issue by YadongD** [CINPLA/pyopenephys#31]

**Comment by alejoe91** [comment]
Hi, this might be. a bug. I'll look into it. Can you share with me a test file to try out?

**Comment by YadongD** [comment]
Hi Alessio,

Here is the Google drive link of a test folder:
https://drive.google.com/drive/folders/1DinjeDIeyDUhxNpwniZ5jBOcdzb2IYsI?usp=sharing

Thank you!

**Comment by alejoe91** [comment]
@YadongD I requested access, can you approve it?

**Comment by YadongD** [comment]
@alejoe91 Folder access approved.

**Comment by alejoe91** [comment]
> @alejoe91 Folder access approved.

looking into it now

**Comment by alejoe91** [comment]
@YadongD 

A new version (1.1.5) that fixes this issue is released: https://pypi.org/project/pyopenephys/

Can you try again after `pip install --upgrade pyopenephys`?
