### ISSUE TITLE
XML attribute key error for open ephys file format <0.4.0

### ISSUE THREAD

**Issue by miketrumpis** [CINPLA/pyopenephys#33]
In the content of using nwb_conversion_tools, I triggered a KeyError trying to instantiate an Experiment object with some old open ephys data. I read that support for this file format will be dropped from this library, but want to document the issue at the end of the traceback.

The issue is that the XML attributes changed a bit from 0.3.5 to 0.4.x. Here's an example of a version 0.4.1 processor tag (has expected attributes):

```xml
<PROCESSOR name="Sources/Rhythm FPGA" insertionPoint="1" pluginName="" pluginType="-1"
               pluginIndex="0" libraryName="" libraryVersion="-1" isSource="1"
               isSink="0" NodeId="100">
```

Here's an example of an older processor tag:

```xml
<PROCESSOR name="Sources/Rhythm FPGA" insertionPoint="1" NodeId="100">
```

The KeyError happens here, trying to find the "isSource" attribute

https://github.com/CINPLA/pyopenephys/blob/dc38899bc938e78946cfc6b08f4d01a78ed8b298/pyopenephys/core.py#L275-L277

In addition, there would also be an error with the way "recordEngine" was encoded in the older format.

https://github.com/CINPLA/pyopenephys/blob/dc38899bc938e78946cfc6b08f4d01a78ed8b298/pyopenephys/core.py#L303-L307

Here's a gist for the whole xml https://gist.github.com/miketrumpis/66037f6f4d5cdfbc0f51a52580b490f0

**Comment by alejoe91** [comment]
Thanks @miketrumpis 

Would you have time to make a patch that works for open ephys files and make a PR? I'd be happy to review it!

Cheers
Alessio

**Comment by miketrumpis** [comment]
No problem. I've been stepping through a monkey-patch and also came across some different specs for the `messages.events` file. Do you know of any documentation for that file for versions prior to 0.4 (or even for >= 0.4)? Otherwise I can make some educated guesses to interpolate the info.

**Comment by alejoe91** [comment]
Thanks @miketrumpis 

I only know [this one](https://open-ephys.github.io/gui-docs/User-Manual/Recording-data/index.html).. 
let's make an educated guess here for now. Note that the new SI version (which will be used also by nwb-conversion-tools when fully ready) is using [NEO](https://github.com/NeuralEnsemble/python-neo) as backend to handle all I/O. So we need to check that also NEO supports these old OE versions.

**Comment by miketrumpis** [comment]
PR is up: seems to work on a couple of examples of pre-0.4 open ephys recordings.

As for NEO, there doesn't seem to be a problem with the older files. The object instantiates, and I can pull data blocks that look like arrays. I haven't really checked whether they look neural, but no reason to doubt it.

**Comment by miketrumpis** [comment]
looks like this can close
