### ISSUE TITLE
I am very naive for using this code

### ISSUE THREAD

**Issue by engramer** [CINPLA/pyopenephys#36]
Hi, I am trying to use the code to analyze my recording data with open ephys, but found this error. 

File "/Users/sungmo/anaconda/lib/python3.5/site-packages/pyopenephys/core.py", line 524
    sync_messagefile = self.absolute_foldername / f'messages_{self.experiment.id}.events'
                                                                                        ^
SyntaxError: invalid syntax

Sorry, I am very naive. Could you help me out? 
Thanks

**Comment by alejoe91** [comment]
Hi @engramer 

The f-string is supported from Python>=3.6. You can just update your anaconda distribution to a later version and that should fix the problem.
