### ISSUE TITLE
infinity loop when loading tracking

### ISSUE THREAD

**Issue by T-dogg** [CINPLA/pyopenephys#8]
de-indent this line:
https://github.com/CINPLA/pyopenephys/blob/35cd78291126d535caf79b61e270b2fbce5d0110/pyopenephys/core.py#L715

**Comment by alejoe91** [comment]
290535039846432d391a65af33fb128ec6e2ac33

@lepmik @T-dogg 
In general I recommend saving the tracking rather than calling calling recording.tracking in a loop:
```
tracking = recording.tracking
for t in tracking:
    etc etc etc
```

Should be fixed now anyways!
